In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("bank.csv")

In [3]:
dataset

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [4]:
dataset.head(20)

age          job   marital  education default  balance housing loan  \
0    59       admin.   married  secondary      no     2343     yes   no   
1    56       admin.   married  secondary      no       45      no   no   
2    41   technician   married  secondary      no     1270     yes   no   
3    55     services   married  secondary      no     2476     yes   no   
4    54       admin.   married   tertiary      no      184      no   no   
5    42   management    single   tertiary      no        0     yes  yes   
6    56   management   married   tertiary      no      830     yes  yes   
7    60      retired  divorced  secondary      no      545     yes   no   
8    37   technician   married  secondary      no        1     yes   no   
9    28     services    single  secondary      no     5090     yes   no   
10   38       admin.    single  secondary      no      100     yes   no   
11   30  blue-collar   married  secondary      no      309     yes   no   
12   29   management   married   tertiary      no      199     yes  yes   
13   46  blue-collar    single   tertiary      no      460     yes   no   
14   31   technician    single   tertiary      no      703     yes   no   
15   35   management  divorced   tertiary      no     3837     yes   no   
16   32  blue-collar    single    primary      no      611     yes   no   
17   49     services   married  secondary      no       -8     yes   no   
18   41       admin.   married  secondary      no       55     yes   no   
19   49       admin.  divorced  secondary      no      168     yes  yes   

    contact  day month  duration  campaign  pdays  previous poutcome deposit  
0   unknown    5   may      1042         1     -1         0  unknown     yes  
1   unknown    5   may      1467         1     -1         0  unknown     yes  
2   unknown    5   may      1389         1     -1         0  unknown     yes  
3   unknown    5   may       579         1     -1         0  unknown     yes  
4   unknown    5   may       673         2     -1         0  unknown     yes  
5   unknown    5   may       562         2     -1         0  unknown     yes  
6   unknown    6   may      1201         1     -1         0  unknown     yes  
7   unknown    6   may      1030         1     -1         0  unknown     yes  
8   unknown    6   may       608         1     -1         0  unknown     yes  
9   unknown    6   may      1297         3     -1         0  unknown     yes  
10  unknown    7   may       786         1     -1         0  unknown     yes  
11  unknown    7   may      1574         2     -1         0  unknown     yes  
12  unknown    7   may      1689         4     -1         0  unknown     yes  
13  unknown    7   may      1102         2     -1         0  unknown     yes  
14  unknown    8   may       943         2     -1         0  unknown     yes  
15  unknown    8   may      1084         1     -1         0  unknown     yes  
16  unknown    8   may       541         3     -1         0  unknown     yes  
17  unknown    8   may      1119         1     -1         0  unknown     yes  
18  unknown    8   may      1120         2     -1         0  unknown     yes  
19  unknown    8   may       513         1     -1         0  unknown     yes

In [5]:
dataset.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [7]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [8]:
dataset.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [9]:
dataset["age"].mean()

41.231947679627304

In [11]:
dataset["housing"].mode()[0]

'no'

In [12]:
dataset["job"].mode()[0]

'management'

In [13]:
x = dataset.iloc[:, 3:13]
y = dataset.iloc[:, 13]

In [14]:
x

education default  balance housing loan   contact  day month  duration  \
0      secondary      no     2343     yes   no   unknown    5   may      1042   
1      secondary      no       45      no   no   unknown    5   may      1467   
2      secondary      no     1270     yes   no   unknown    5   may      1389   
3      secondary      no     2476     yes   no   unknown    5   may       579   
4       tertiary      no      184      no   no   unknown    5   may       673   
...          ...     ...      ...     ...  ...       ...  ...   ...       ...   
11157    primary      no        1     yes   no  cellular   20   apr       257   
11158  secondary      no      733      no   no   unknown   16   jun        83   
11159  secondary      no       29      no   no  cellular   19   aug       156   
11160  secondary      no        0      no  yes  cellular    8   may         9   
11161  secondary      no        0      no   no  cellular    9   jul       628   

       campaign  
0             1  
1             1  
2             1  
3             1  
4             2  
...         ...  
11157         1  
11158         4  
11159         2  
11160         2  
11161         1  

[11162 rows x 10 columns]

In [15]:
y

0         -1
1         -1
2         -1
3         -1
4         -1
        ... 
11157     -1
11158     -1
11159     -1
11160    172
11161     -1
Name: pdays, Length: 11162, dtype: int64

In [16]:
type (x)

pandas.core.frame.DataFrame

In [17]:
type (y)

pandas.core.series.Series

In [18]:
x = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [19]:
x

array([['secondary', 'no', 2343, ..., 'may', 1042, 1],
       ['secondary', 'no', 45, ..., 'may', 1467, 1],
       ['secondary', 'no', 1270, ..., 'may', 1389, 1],
       ...,
       ['secondary', 'no', 29, ..., 'aug', 156, 2],
       ['secondary', 'no', 0, ..., 'may', 9, 2],
       ['secondary', 'no', 0, ..., 'jul', 628, 1]], dtype=object)

In [20]:
y

array([ -1,  -1,  -1, ...,  -1, 172,  -1], dtype=int64)

In [21]:
type(x)

numpy.ndarray

In [22]:
type(y)

numpy.ndarray

In [24]:
dataset["job"].unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

In [25]:
dataset["contact"].unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [26]:
x.shape

(11162, 10)

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [34]:
print(x.shape,"xshape")
print(y.shape,"yshape")
print(x_train.shape,"x_train shape")
print(x_test.shape,"x_test shape")
print(y_train.shape,"y_train shape")
print(y_test.shape,"y_test shape")

(11162, 10) xshape
(11162,) yshape
(8929, 10) x_train shape
(2233, 10) x_test shape
(8929,) y_train shape
(2233,) y_test shape


In [44]:
p = np.array([[1,2,3],[-25,8,10000],[4,5,6]])
p

array([[    1,     2,     3],
       [  -25,     8, 10000],
       [    4,     5,     6]])

In [49]:
from sklearn.preprocessing import StandardScaler
d = StandardScaler()
p = d.fit_transform(p)

In [50]:
p

array([[ 0.58877664, -1.22474487, -0.7074251 ],
       [-1.40794413,  1.22474487,  1.41421351],
       [ 0.8191675 ,  0.        , -0.70678842]])

In [51]:
dataset.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [52]:
dataset["age"]

0        59
1        56
2        41
3        55
4        54
         ..
11157    33
11158    39
11159    32
11160    43
11161    34
Name: age, Length: 11162, dtype: int64

In [55]:
x_train[0:5,:]

array([['secondary', 'no', 104, 'yes', 'no', 'unknown', 8, 'may', 285, 1],
       ['secondary', 'no', 514, 'no', 'no', 'cellular', 3, 'feb', 261, 1],
       ['primary', 'no', 195, 'no', 'no', 'cellular', 16, 'nov', 984, 5],
       ['secondary', 'no', 687, 'yes', 'no', 'cellular', 7, 'aug', 221,
        1],
       ['secondary', 'no', 1077, 'yes', 'no', 'cellular', 18, 'may', 432,
        3]], dtype=object)

In [60]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

ValueError: could not convert string to float: 'secondary'