In [1]:
#importing dataset
import numpy as np
import pandas as pd

In [2]:
#reading dataset
dataset = pd.read_csv("50_Startups.csv")

In [3]:
dataset

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
#check missing values
#no null values
dataset.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [5]:
#gives the count of null values from the dataset
dataset.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [6]:
#filling in the null values with mean and mode values, inplace is true is 
dataset["Administration"].fillna(dataset["Administration"].mean(), inplace = True)
dataset["Marketing Spend"].fillna(dataset["Marketing Spend"].mean(), inplace = True)

In [7]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [8]:
#spitting data into x and y
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [9]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 212725.26673469393, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 121564.03816326526, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16

In [10]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [11]:
#unique value in column geography
dataset["State"].unique()
#3 + 3 = 6

array(['New York', 'California', 'Florida'], dtype=object)

In [12]:
x.shape

(50, 4)

In [13]:
#to transform the data into binary format
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [14]:
#syntax for column transformer
  #objectname = ColumnTransformer([(binaray conversion instance name(oh/one), binary transformation stategy , [index no of columns need to be transformed])],remainder = "passthrough")
ct = ColumnTransformer([("one",OneHotEncoder(),[3])], remainder = "passthrough")
x = ct.fit_transform(x)
#in x 1 and 2 columns, undergoes onehotencoder and it is replaced with x variable 

In [15]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 212725.26673469393],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 121564.03816326526, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 9

In [16]:
x[0]

array([0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1], dtype=object)

In [17]:
x.shape

(50, 6)

In [19]:
#importing the library split for train and test data- 20%(0.2) should be test data, 80%(0.8) train data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [20]:
print(x.shape,"xshape")
print(y.shape,"yshape")
print(x_train.shape,"x_train shape")
print(x_test.shape,"x_test shape")
print(y_train.shape,"y_train shape")
print(y_test.shape,"y_test shape")

(50, 6) xshape
(50,) yshape
(40, 6) x_train shape
(10, 6) x_test shape
(40,) y_train shape
(10,) y_test shape


In [21]:
#scalling is done 
from sklearn.preprocessing import StandardScaler


In [22]:
dataset.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121564.038163    212725.266735  112012.639200
std     45902.256482    27974.818762    121697.951409   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    135028.207500   90138.902500
50%     73051.080000   122699.795000    213680.038367  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [23]:
dataset["R&D Spend"]

0     165349.20
1     162597.70
2     153441.51
3     144372.41
4     142107.34
5     131876.90
6     134615.46
7     130298.13
8     120542.52
9     123334.88
10    101913.08
11    100671.96
12     93863.75
13     91992.39
14    119943.24
15    114523.61
16     78013.11
17     94657.16
18     91749.16
19     86419.70
20     76253.86
21     78389.47
22     73994.56
23     67532.53
24     77044.01
25     64664.71
26     75328.87
27     72107.60
28     66051.52
29     65605.48
30     61994.48
31     61136.38
32     63408.86
33     55493.95
34     46426.07
35     46014.02
36     28663.76
37     44069.95
38     20229.59
39     38558.51
40     28754.33
41     27892.92
42     23640.93
43     15505.73
44     22177.74
45      1000.23
46      1315.46
47         0.00
48       542.05
49         0.00
Name: R&D Spend, dtype: float64

In [24]:
#using the formulae to scale
#formulae = value - mean/std deviation
(165349.20-73721.615600)/45902.256482

1.9961455366781506

In [25]:
#first five rows with all columns before scaling
x_train[0:5,:]

array([[0.0, 1.0, 0.0, 55493.95, 103057.49, 214634.81],
       [0.0, 0.0, 1.0, 46014.02, 85047.44, 205517.64],
       [0.0, 1.0, 0.0, 75328.87, 144135.98, 134050.07],
       [1.0, 0.0, 0.0, 46426.07, 157693.92, 210797.67],
       [0.0, 1.0, 0.0, 91749.16, 114175.79, 294919.57]], dtype=object)

In [26]:
#before scaling
y_train

array([ 96778.92,  96479.51, 105733.54,  96712.8 , 124266.9 , 155752.6 ,
       132602.65,  64926.08,  35673.41, 101004.64, 129917.04,  99937.59,
        97427.84, 126992.93,  71498.49, 118474.03,  69758.98, 152211.77,
       134307.35, 107404.34, 156991.12, 125370.37,  78239.91,  14681.4 ,
       191792.06, 141585.52,  89949.14, 108552.04, 156122.51, 108733.99,
        90708.19, 111313.02, 122776.86, 149759.96,  81005.76,  49490.75,
       182901.99, 192261.83,  42559.73,  65200.33])

In [27]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)


In [28]:
#first five rows with all columns after scaling
x_train[0:5,:]

array([[-0.81649658,  1.73205081, -0.73379939, -0.35006454, -0.78547109,
         0.08437197],
       [-0.81649658, -0.57735027,  1.36277029, -0.55530319, -1.48117426,
         0.010183  ],
       [-0.81649658,  1.73205081, -0.73379939,  0.07935762,  0.80133381,
        -0.57136866],
       [ 1.22474487, -0.57735027, -0.73379939, -0.54638238,  1.32505817,
         0.05314808],
       [-0.81649658,  1.73205081, -0.73379939,  0.43485371, -0.35598663,
         0.73767158]])

In [29]:
y_train

array([ 96778.92,  96479.51, 105733.54,  96712.8 , 124266.9 , 155752.6 ,
       132602.65,  64926.08,  35673.41, 101004.64, 129917.04,  99937.59,
        97427.84, 126992.93,  71498.49, 118474.03,  69758.98, 152211.77,
       134307.35, 107404.34, 156991.12, 125370.37,  78239.91,  14681.4 ,
       191792.06, 141585.52,  89949.14, 108552.04, 156122.51, 108733.99,
        90708.19, 111313.02, 122776.86, 149759.96,  81005.76,  49490.75,
       182901.99, 192261.83,  42559.73,  65200.33])

In [30]:
#building the model
# this library is used to initialise the model
from tensorflow.keras.models import Sequential 
# this is to add layers
from tensorflow.keras.layers import Dense 

In [31]:
# modelname = Sequential()
Regression = Sequential() 

In [32]:
x_train.shape

(40, 6)

In [33]:
#input layer
#units = no of inputs 
#kernal_initializer is random so it will randomly generate the weights
Regression.add(Dense(units = 4, kernel_initializer = "random_uniform", activation = "relu"))

In [34]:
#hidden layer 
# in hiddel layer the ideal count of neurons would be 2* no of neuron in inpout layer
Regression.add(Dense(units = 8 , kernel_initializer = "random_uniform", activation = "relu"))
Regression.add(Dense(units = 8 , kernel_initializer = "random_uniform", activation = "relu"))
Regression.add(Dense(units = 8 , kernel_initializer = "random_uniform", activation = "relu"))
Regression.add(Dense(units = 8 , kernel_initializer = "random_uniform", activation = "relu"))
Regression.add(Dense(units = 8 , kernel_initializer = "random_uniform", activation = "relu"))


In [35]:
#output layer
#outout is either 1 or 0 
Regression.add(Dense(units = 1 , kernel_initializer = "random_uniform", activation = "relu"))

In [36]:
#compiler - gradient descent 
#sgd is not used because the accuracy is not good
#adam is like batch GD
Regression.compile(optimizer = "sgd", loss = "mean_squared_error", metrics = ["accuracy"])

In [37]:
#training the model 
Regression.fit(x_train, y_train, epochs =100)

Epoch 1/100
2/2 [==============================] - 1s 0s/step - loss: 13519275008.0000 - accuracy: 0.0000e+00
Epoch 2/100
2/2 [==============================] - 0s 3ms/step - loss: 52881217896316928.0000 - accuracy: 0.0000e+00
Epoch 3/100
2/2 [==============================] - 0s 3ms/step - loss: 13615994880.0000 - accuracy: 0.0000e+00
Epoch 4/100
2/2 [==============================] - 0s 4ms/step - loss: 13615994880.0000 - accuracy: 0.0000e+00
Epoch 5/100
2/2 [==============================] - 0s 4ms/step - loss: 13615994880.0000 - accuracy: 0.0000e+00
Epoch 6/100
2/2 [==============================] - 0s 3ms/step - loss: 13615994880.0000 - accuracy: 0.0000e+00
Epoch 7/100
2/2 [==============================] - 0s 3ms/step - loss: 13615994880.0000 - accuracy: 0.0000e+00
Epoch 8/100
2/2 [==============================] - 0s 5ms/step - loss: 13615995904.0000 - accuracy: 0.0000e+00
Epoch 9/100
2/2 [==============================] - 0s 4ms/step - loss: 13615994880.0000 - accuracy: 0.0000e

In [38]:
#testing the model with x_test(questions)
ypred = Regression.predict(x_test)


In [39]:
ypred 

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [40]:
ypred[0]

array([0.], dtype=float32)

In [41]:
ypred =  ypred > 0
ypred

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [42]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [43]:
ypred[0:10]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

In [44]:
y_test[0:10]

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [45]:
dataset.head(3)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39

In [46]:
yp = Regression.predict(sc.transform(ct.transform([[165349.2, 136897.8, 471784.1,"New York"]])))

In [47]:
yp > 0
if(yp > 0):
    print("High profit")
else:
    print("Low profit")

Low profit


In [48]:
sc.transform(ct.transform([[165349.2, 136897.8, 471784.1,"New York"]]))

array([[-0.33333333, -1.22474487,  1.52752523,  2.01925133,  0.68671227,
         2.17417866]])