In [1]:
#1. Importing libraries
import numpy as np
import pandas as pd

In [2]:
#2. reading the dataset
dataset = pd.read_csv("bank.csv")

In [3]:
dataset

age          job  marital  education default  balance housing loan  \
0       59       admin.  married  secondary      no     2343     yes   no   
1       56       admin.  married  secondary      no       45      no   no   
2       41   technician  married  secondary      no     1270     yes   no   
3       55     services  married  secondary      no     2476     yes   no   
4       54       admin.  married   tertiary      no      184      no   no   
...    ...          ...      ...        ...     ...      ...     ...  ...   
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
0       unknown    5   may      1042         1     -1         0  unknown   
1       unknown    5   may      1467         1     -1         0  unknown   
2       unknown    5   may      1389         1     -1         0  unknown   
3       unknown    5   may       579         1     -1         0  unknown   
4       unknown    5   may       673         2     -1         0  unknown   
...         ...  ...   ...       ...       ...    ...       ...      ...   
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
0         yes  
1         yes  
2         yes  
3         yes  
4         yes  
...       ...  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no  

[11162 rows x 17 columns]

In [5]:
dataset.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [6]:
#3. handling missing values
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [7]:
dataset.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [8]:
dataset.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [9]:
dataset["age"].mean()

41.231947679627304

In [10]:
dataset["housing"].mode()[0]

'no'

In [11]:
dataset["job"].mode()[0]

'management'

In [12]:
#4. splitting the data into x and y
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 16:17].values

In [13]:
x

array([[59, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [56, 'admin.', 'married', ..., -1, 0, 'unknown'],
       [41, 'technician', 'married', ..., -1, 0, 'unknown'],
       ...,
       [32, 'technician', 'single', ..., -1, 0, 'unknown'],
       [43, 'technician', 'married', ..., 172, 5, 'failure'],
       [34, 'technician', 'married', ..., -1, 0, 'unknown']], dtype=object)

In [14]:
y

array([['yes'],
       ['yes'],
       ['yes'],
       ...,
       ['no'],
       ['no'],
       ['no']], dtype=object)

In [15]:
print(dataset["job"].unique())
print(dataset["marital"].unique())
print(dataset["education"].unique())
print (dataset["default"].unique())
print (dataset["housing"].unique())
print(dataset["loan"].unique())
print(dataset["month"].unique())
print(dataset["contact"].unique())
print(dataset["poutcome"].unique())

#44 + 7 = 51

['admin.' 'technician' 'services' 'management' 'retired' 'blue-collar'
 'unemployed' 'entrepreneur' 'housemaid' 'unknown' 'self-employed'
 'student']
['married' 'single' 'divorced']
['secondary' 'tertiary' 'primary' 'unknown']
['no' 'yes']
['yes' 'no']
['no' 'yes']
['may' 'jun' 'jul' 'aug' 'oct' 'nov' 'dec' 'jan' 'feb' 'mar' 'apr' 'sep']
['unknown' 'cellular' 'telephone']
['unknown' 'other' 'failure' 'success']


In [16]:
x.shape

(11162, 16)

In [17]:
#5. handling categorical data 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [18]:
ct = ColumnTransformer([("one", OneHotEncoder(), [1, 2, 3, 4, 6, 7, 8, 10, 15])], remainder = "passthrough")
x = ct.fit_transform(x)

In [19]:
x

array([[1.0, 0.0, 0.0, ..., 1, -1, 0],
       [1.0, 0.0, 0.0, ..., 1, -1, 0],
       [0.0, 0.0, 0.0, ..., 1, -1, 0],
       ...,
       [0.0, 0.0, 0.0, ..., 2, -1, 0],
       [0.0, 0.0, 0.0, ..., 2, 172, 5],
       [0.0, 0.0, 0.0, ..., 1, -1, 0]], dtype=object)

In [20]:
x[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
       1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
       0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
       0.0, 0.0, 0.0, 0.0, 1.0, 59, 2343, 5, 1042, 1, -1, 0], dtype=object)

In [21]:
x.shape
#before = 16, now = 51

(11162, 51)

In [72]:

y = dataset.deposit.replace(to_replace=['no', 'yes'], value=[0, 1])

In [73]:
y

0        1
1        1
2        1
3        1
4        1
        ..
11157    0
11158    0
11159    0
11160    0
11161    0
Name: deposit, Length: 11162, dtype: int64

In [74]:
#6. splitting the data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [75]:
print(x.shape,"xshape")
print(y.shape,"yshape")
print(x_train.shape,"x_train shape")
print(x_test.shape,"x_test shape")
print(y_train.shape,"y_train shape")
print(y_test.shape,"y_test shape")

(11162, 51) xshape
(11162,) yshape
(8929, 51) x_train shape
(2233, 51) x_test shape
(8929,) y_train shape
(2233,) y_test shape


In [76]:
#7. applying feature scaling
from sklearn.preprocessing import StandardScaler

In [77]:
dataset.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [78]:
dataset["age"]

0        59
1        56
2        41
3        55
4        54
         ..
11157    33
11158    39
11159    32
11160    43
11161    34
Name: age, Length: 11162, dtype: int64

In [79]:
#using the formulae to scale
#formulae = value - mean/std deviation
(59-41.23)/11.91

1.4920235096557517

In [80]:
#first five rows with all columns before scaling
x_train[0:5,:]

array([[0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0,
        0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 49, 104, 8, 285, 1, -1, 0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 59, 514, 3, 261, 1, -1, 0],
       [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 1.0, 33, 195, 16, 984, 5, -1, 0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0,
        0.0, 

In [81]:
#before scaling
y_train

6111     0
1149     1
2954     1
2458     1
7504     0
        ..
4859     1
3264     1
9845     0
10799    0
2732     1
Name: deposit, Length: 8929, dtype: int64

In [102]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [103]:
#first five rows with all columns after scaling
x_train[0:5,:]

array([[-0.37172192, -0.45760242, -0.17658264, -0.1589378 ,  1.8452729 ,
        -0.27363591, -0.1931085 , -0.30435733, -0.17992689, -0.44212513,
        -0.18025832, -0.08293772, -0.36485864,  0.86351031, -0.66975544,
        -0.39346051,  1.01614555, -0.69993206, -0.21741017,  0.12621015,
        -0.12621015, -1.05825117,  1.05825117,  0.39003722, -0.39003722,
        -1.60273048, -0.27292594,  1.93439945, -0.30193478, -0.39913565,
        -0.09686471, -0.27410848, -0.17488949, -0.39459853, -0.34910544,
        -0.15930776,  1.70870313, -0.30215554, -0.1931085 , -0.16761389,
        -0.35031555, -0.22657536, -0.32939951,  0.58661881,  0.64941897,
        -0.44565283, -0.90504798, -0.2483547 , -0.56394809, -0.48428507,
        -0.35888264],
       [-0.37172192, -0.45760242, -0.17658264, -0.1589378 , -0.54192526,
         3.65449114, -0.1931085 , -0.30435733, -0.17992689, -0.44212513,
        -0.18025832, -0.08293772,  2.7407875 , -1.15806377, -0.66975544,
        -0.39346051,  1.01614

In [104]:
#after scaling
y_train

6111     0
1149     1
2954     1
2458     1
7504     0
        ..
4859     1
3264     1
9845     0
10799    0
2732     1
Name: deposit, Length: 8929, dtype: int64

In [105]:
#building the model
# this library is used to initialise the model
from tensorflow.keras.models import Sequential 
# this is to add layers
from tensorflow.keras.layers import Dense 

In [106]:
# modelname = Sequential()
Regression = Sequential() 

In [107]:
x_train.shape

(8929, 51)

In [108]:
#input layer
#units = no of inputs 
#kernal_initializer is random so it will randomly generate the weights
Regression.add(Dense(units = 16, kernel_initializer = "random_uniform", activation = "relu"))

In [109]:
#hidden layer
# in hiddel layer the ideal count of neurons would be 2* no of neuron in inpout layer
Regression.add(Dense(units = 32  , kernel_initializer = "random_uniform", activation = "relu"))
Regression.add(Dense(units = 32  , kernel_initializer = "random_uniform", activation = "relu"))
Regression.add(Dense(units = 32 , kernel_initializer = "random_uniform", activation = "relu"))
Regression.add(Dense(units = 32  , kernel_initializer = "random_uniform", activation = "relu"))
Regression.add(Dense(units = 32 , kernel_initializer = "random_uniform", activation = "relu"))

In [110]:
#output layer
#outout is either 1 or 0 
Regression.add(Dense(units = 1 , kernel_initializer = "random_uniform", activation = "relu"))

In [111]:
#compiler - gradient descent 
#sgd is not used because the accuracy is not good
#adam is like batch GD
Regression.compile(optimizer = "rmsprop", loss = "mean_squared_error", metrics = ["accuracy"])

In [112]:
#training the model 
#epochs = 350, model will be trained 350 times 
Regression.fit(x_train, y_train, epochs = 100)

Epoch 1/100
280/280 [==============================] - 1s 783us/step - loss: 0.1848 - accuracy: 0.7552
Epoch 2/100
280/280 [==============================] - 0s 968us/step - loss: 0.1481 - accuracy: 0.8075
Epoch 3/100
280/280 [==============================] - 0s 1ms/step - loss: 0.1433 - accuracy: 0.8136
Epoch 4/100
280/280 [==============================] - 1s 2ms/step - loss: 0.1385 - accuracy: 0.8228
Epoch 5/100
280/280 [==============================] - 1s 2ms/step - loss: 0.1301 - accuracy: 0.8331
Epoch 6/100
280/280 [==============================] - 0s 2ms/step - loss: 0.1225 - accuracy: 0.8471
Epoch 7/100
280/280 [==============================] - 0s 2ms/step - loss: 0.1164 - accuracy: 0.8465
Epoch 8/100
280/280 [==============================] - 0s 2ms/step - loss: 0.1122 - accuracy: 0.8508
Epoch 9/100
280/280 [==============================] - 0s 2ms/step - loss: 0.1104 - accuracy: 0.8543
Epoch 10/100
280/280 [==============================] - 0s 2ms/step - loss: 0.1078 - ac

In [113]:
#testing the model with x_test(questions)
ypred = Regression.predict(x_test)
ypred 
#the values are between 0 to 1 because sigmoid is used

array([[0.09803137],
       [1.1313208 ],
       [0.        ],
       ...,
       [1.0196987 ],
       [0.        ],
       [0.53809416]], dtype=float32)

In [114]:
ypred =  ypred > 0
ypred

array([[ True],
       [ True],
       [False],
       ...,
       [ True],
       [False],
       [ True]])

In [115]:
y_test

9058    0
3279    1
6502    0
9327    0
9965    0
       ..
6003    0
5606    0
4808    1
3697    1
9952    0
Name: deposit, Length: 2233, dtype: int64

In [116]:
ypred[0:10]

array([[ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False]])

In [117]:
y_test[0:10]

9058     0
3279     1
6502     0
9327     0
9965     0
3212     1
3032     1
10620    0
4606     1
1978     1
Name: deposit, dtype: int64

In [118]:
dataset.head(3)

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes

In [119]:
yp = Regression.predict(sc.transform(ct.transform([[56, "admin.", "married", "secondary", "no", 45, "no", "no", "unknown", 5, "may", 1467, 1, -1, 0, "unknown"]])))

In [124]:
yp > 1
if(yp > 1):
    print("Makes a Deposit")
else:
    print("Does not deposit")

Makes a Deposit
